# Main option config
system:
  plugin_dir: plugins
  floor: True
  tty: /dev/ttyUSB0
  debug: False
  debug_logging: True
  pipe: /tmp/dance_pipe

# Module layout config (we may change this later)
modules:
  3:
    width: 6
    height: 8
    x_position: 0
    y_position: 0
    orientation: W

  2:
    width: 6
    height: 8
    x_position: 0
    y_position: 6
    orientation: E

  1:
    width: 6
    height: 8
    x_position: 0
    y_position: 12
    orientation: W

  6:
    width: 6
    height: 8
    x_position: 8
    y_position: 12
    orientation: W
    
  5:
    width: 6
    height: 8
    x_position: 8
    y_position: 6
    orientation: W
    
  4:
    width: 6
    height: 8
    x_position: 8
    y_position: 0
    orientation: E
    
  9:
    width: 6
    height: 8
    x_position: 16
    y_position: 0
    orientation: W
    
  8:
    width: 6
    height: 8
    x_position: 16
    y_position: 6
    orientation: E
    
  7:
    width: 6
    height: 8
    x_position: 16
    y_position: 12
    orientation: E
